Final review (pre-publishing)
UnlyEd/github-action-deploy-on-vercel pull request #10
Opened 2021-05-06 09:22 UTC by Vadorequest

2021-05-06 15:10 UTC, Demmonius requested changes

2021-05-06 15:10 UTC, Demmonius commented on .github/workflows/run-example-deployment.yml
>  #          path: "github-action-deploy-on-vercel" # Act doesn't work if not specifying the path. See https://github.com/nektos/act/issues/228
Yes we can remove it because ACT is not implemented yet (and I guess it'll never)
```suggestion
```

2021-05-08 10:20 UTC, Demmonius commented
@Vadorequest may I have a review about the changes that I made please ? :)

2021-05-08 10:33 UTC, Vadorequest commented on lib/main.js
> +    core.debug(`actionReturn: ${actionReturn}`);
si c'est toujours du type string faut le préciser dans la signature

2021-05-08 11:00 UTC, Demmonius commented on lib/main.js
> +    core.debug(`actionReturn: ${actionReturn}`);
Done ! The action doesn't return anything so I replaced it by a log

2021-05-08 11:35 UTC, merged